/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.forum2.gaal.dembra;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int elephant3=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int clearScans=0x7f050001;
        public static final int dbDump=0x7f050004;
        public static final int enterScanMode=0x7f050000;
        public static final int scanHelp=0x7f050003;
        public static final int sendDb=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int cancel=0x7f040006;
        public static final int clear_memory=0x7f040002;
        public static final int confirmHelp=0x7f040004;
        public static final int confirmTitle=0x7f040003;
        public static final int db_empty=0x7f04000b;
        public static final int enter_scan_mode=0x7f040000;
        public static final int ok=0x7f040005;
        public static final int result_failed=0x7f040007;
        public static final int result_failed_why=0x7f040008;
        public static final int result_succeeded=0x7f040009;
        /**  Hit 'Back' to stop scanning. 'Clear' deletes all scanning history. 'Send' scanned info by email.
         */
        public static final int scan_help=0x7f04000a;
        public static final int send_db=0x7f04000d;
        public static final int send_db_postamble=0x7f04000f;
        public static final int send_db_preamble=0x7f04000e;
        public static final int send_db_subject=0x7f040010;
        public static final int send_this_list=0x7f040011;
        public static final int stop_scan_help=0x7f04000c;
    }
}
